#!/usr/bin/env python3
"""incipit.py -- Incipit, the multiturn glass-box chat front-end for Colophon.

An incipit is a book's opening words -- the complement of a colophon. Where
Marginalia inspects one prompt, Incipit inspects a CONVERSATION: chat bubbles
on top, and underneath them the truth -- one growing text tape, the literal
K-character window the model re-reads, and per-character records (probability,
entropy, top-k, occlusion saliency) computed from the weights via
colophon.inspect_prompt(). glassboxllm (2025) mocked this UI with simulated
metrics; every number here is real.

The server is STATELESS BY DESIGN: the client sends the full turn list on
every request and the server holds no conversation. That mirrors how real LLM
APIs work and is itself part of the lesson -- "memory" is just text re-sent
and re-read. It is also why /api/turn responses are deterministic given the
same request + seed.

Three modes, three acts (the teaching sequence lives in the front-end; the
copy here drives the mode switcher):
  elements64  YAML-trained periodic-table model, K=64  (Acts 1-2)
  dialogue    dialogue-trained periodic-table model, K=64  (Act 3)
  osai        the K=12 flagship, for tiny-window drama (free play)
Act 2 and Act 3 share hyperparameters on purpose: the only variable between
"chat format fails" and "chat format works" is the training data's format.

Zero new runtime dependencies: stdlib http.server + numpy, same as Marginalia.
The React front-end in incipit/ is a build-time artifact; this server serves
its incipit/dist/ output, so production runs with Python alone.

Usage:
  python colophon.py --src teaching_data/elements --out elements_k64.npz \
      --steps 60000 --K 64 --E 64 --H 512 --lr 0.0005 train
  python colophon.py --src teaching_data/dialogue --out dialogue_k64.npz \
      --steps 60000 --K 64 --E 64 --H 512 --lr 0.0005 train
  (cd incipit && npm install && npm run build)     # once, for the UI
  python incipit.py                                 # http://127.0.0.1:8790
"""
from __future__ import annotations
import argparse, http.server, json, mimetypes, os, urllib.parse

import colophon
import marginalia

HERE = os.path.dirname(os.path.abspath(__file__))
DIST_DIR = os.path.join(HERE, "incipit", "dist")

MAX_TAPE_CHARS = 10_000      # bound the per-request forward-pass cost
MAX_CONTINUATION = 400       # hard cap on sampled chars per turn
DEFAULT_CONTINUATION = 160
MAX_TURNS = 200
ROLES = ("user", "model")
FORMATS = ("raw", "chat")

# Copy lives server-side (Marginalia's convention) so /api/modes drives the
# mode switcher and nothing is re-authored in JavaScript. The front-end's
# three-act rail copy lives client-side in incipit/src/acts.ts -- it is
# teaching narrative, not mode metadata.
MODE_META = {
    "elements64": {
        "label": "Periodic table (YAML, K=64)",
        "blurb": ("Trained on 118 element facts as YAML. Completion works; "
                  "chat format doesn't -- not because the window is small "
                  "(it is the same K=64 as the dialogue model) but because "
                  "its training data contains no conversations."),
        "acts": [1, 2],
        "format_default": "raw",
        "train_hint": ("python colophon.py --src teaching_data/elements "
                       "--out elements_k64.npz --steps 60000 --K 64 --E 64 "
                       "--H 512 --lr 0.0005 train"),
        "source_note": ("118 undisputed IUPAC facts as YAML, generated "
                        "byte-for-byte by the committed "
                        "teaching_data/build_elements.py."),
    },
    "dialogue": {
        "label": "Periodic table (dialogue, K=64)",
        "blurb": ("Same architecture, same facts -- but the training data is "
                  "user:/model: conversations, so chat format works. A "
                  "chatbot is a completion model whose corpus contains "
                  "dialogue."),
        "acts": [3],
        "format_default": "chat",
        "train_hint": ("python colophon.py --src teaching_data/dialogue "
                       "--out dialogue_k64.npz --steps 60000 --K 64 --E 64 "
                       "--H 512 --lr 0.0005 train"),
        "source_note": ("The same 118 IUPAC element facts, reformatted as "
                        "user:/model: Q&A turns, generated byte-for-byte by "
                        "the committed teaching_data/build_dialogue.py."),
    },
    "osai": {
        "label": "Openness index (K=12)",
        "blurb": ("The flagship Colophon model. Its tiny 12-character window "
                  "makes the sliding-context lesson dramatic: watch it "
                  "forget almost immediately."),
        "acts": [],
        "format_default": "raw",
        "train_hint": "python colophon.py demo",
        "source_note": ("OSAI-schema YAML. Trained on the real European Open "
                        "Source AI Index, this corpus is CC BY 4.0 -- cite "
                        "doi:10.5281/zenodo.15386042. The bundled sample_data "
                        "files are original, fictional stand-ins."),
        "source_url": "https://codeberg.org/AI-Technology-Assessment/main-database",
    },
}
DEFAULT_MODE = "elements64"  # Incipit is the teaching app; Act 1 starts here


def build_tape(turns, fmt):
    """The exact string the model is conditioned on -- returned to the client
    verbatim, because "the conversation IS this string" is the lesson.

    raw : active turn texts concatenated directly (completion mode).
    chat: each active turn as 'role: text\\n', then 'model: ' so generation
          begins where the model's reply would -- byte-identical to the
          dialogue corpus's training format (see build_dialogue.py)."""
    active = [t for t in turns if not t.get("excluded")]
    if fmt == "chat":
        return "".join(f"{t['role']}: {t['text']}\n" for t in active) + "model: "
    return "".join(t["text"] for t in active)


def parse_turn_request(body):
    """Validate and normalize a /api/turn request body. Returns (req, error)
    where exactly one is None; error is (http_status, message). Off-map
    characters in the text are deliberately NOT an error -- they are a
    teaching signal reported in the response."""
    if not isinstance(body, dict):
        return None, (400, "request body must be a JSON object")
    turns = body.get("turns")
    if not isinstance(turns, list) or not turns:
        return None, (400, "turns must be a non-empty list")
    if len(turns) > MAX_TURNS:
        return None, (400, f"too many turns (max {MAX_TURNS})")
    for t in turns:
        if not isinstance(t, dict) or t.get("role") not in ROLES \
                or not isinstance(t.get("text"), str):
            return None, (400, "each turn needs a role in ('user','model') "
                               "and string text")
    fmt = body.get("format", "raw")
    if fmt not in FORMATS:
        return None, (400, f"format must be one of {FORMATS}")
    s = body.get("sampling") or {}
    if not isinstance(s, dict):
        return None, (400, "sampling must be an object")
    try:
        sampling = {
            "temperature": float(s.get("temperature", 0.8)),
            "top_k": int(s.get("top_k", 0)),
            "seed": int(s.get("seed", 0)),
            "max_chars": min(int(s.get("max_chars", DEFAULT_CONTINUATION)),
                             MAX_CONTINUATION),
            "stop": s.get("stop") if isinstance(s.get("stop"), str) else None,
            "banned_chars": s.get("banned_chars") or [],
        }
    except (TypeError, ValueError, OverflowError):
        return None, (400, "sampling values must be numeric")
    if sampling["max_chars"] < 1:
        return None, (400, "max_chars must be >= 1")
    if not (0.0 <= sampling["temperature"] <= 4.0):
        return None, (400, "temperature must be in [0, 4]")
    if sampling["top_k"] < 0:
        return None, (400, "top_k must be >= 0")
    bc = sampling["banned_chars"]
    if not isinstance(bc, list) or any(not isinstance(c, str) or len(c) != 1
                                       for c in bc):
        return None, (400, "banned_chars must be a list of single characters")
    if len(bc) > 20:
        return None, (400, "banned_chars: at most 20")
    if sampling["stop"] is not None and len(sampling["stop"]) > 8:
        return None, (400, "stop must be at most 8 characters")
    tape = build_tape(turns, fmt)
    if len(tape) > MAX_TAPE_CHARS:
        return None, (413, f"tape is {len(tape)} chars; max {MAX_TAPE_CHARS}")
    return {"turns": turns, "format": fmt, "sampling": sampling,
            "tape": tape}, None


def run_turn(model, tape, sampling, files=()):
    """One honest generation step. Every number is computed by colophon.py's
    own functions against the loaded weights; this only assembles the
    payload. Banned chars the vocab doesn't contain are skipped (you cannot
    mask a logit that doesn't exist) and the response says which ones
    actually applied."""
    p, stoi, itos, K = model
    banned_applied = sorted({c for c in sampling["banned_chars"] if c in stoi})
    banned_ids = [stoi[c] for c in banned_applied]
    records = colophon.inspect_prompt(
        p, stoi, itos, K, tape,
        n_continuation=sampling["max_chars"] if tape else 0,
        seed=sampling["seed"], temp=sampling["temperature"],
        top_k=sampling["top_k"], banned_ids=banned_ids,
        stop=sampling["stop"])
    continuation = "".join(r["char"] for r in records if r["is_continuation"])
    entropy, unknown = colophon.prompt_confidence(p, stoi, K, tape)
    return {
        "tape": tape,
        "continuation": continuation,
        "records": records,
        "K": K,
        "entropy": entropy,
        "unknown_chars": unknown,
        "off_map": bool(unknown),
        "banned_applied": banned_applied,
        **marginalia.confidence_readout(entropy, unknown,
                                        has_prompt=bool(tape)),
        "source": marginalia.find_source_echo(files, tape),
    }


MISSING_DIST_HTML = """<!DOCTYPE html>
<html><head><meta charset="utf-8">
<title>Incipit -- build the front-end</title></head>
<body style="font-family: ui-monospace, monospace; max-width: 640px; margin: 3rem auto;">
<h1>&#10087; Incipit</h1>
<p>The API is up, but the front-end bundle hasn't been built yet:</p>
<pre>cd incipit
npm install
npm run build</pre>
<p>then reload this page. (During development, run <code>npm run dev</code>
instead -- Vite's dev server proxies /api here.)</p>
</body></html>
"""


def make_handler(modes, default_mode=DEFAULT_MODE, dist_dir=DIST_DIR):
    """modes maps a mode id to a config dict:
        {"model": (p, stoi, itos, K) or None,  # None if that npz was absent
         "files": [(name, text), ...],          # corpus for the source echo
         "params": int or None,                 # n_params, for the model card
         "label", "blurb", "acts", "format_default", "train_hint"}
    The page and /api/modes serve regardless of which models loaded;
    /api/turn and /api/saliency report 400 for an unknown mode and 503 for a
    known mode whose model is absent -- one missing npz never takes Incipit
    down (Marginalia's degradation contract)."""

    def _modes_payload():
        return {
            "default": default_mode,
            "modes": [
                {"id": mid,
                 "label": cfg.get("label", mid),
                 "blurb": cfg.get("blurb", ""),
                 "acts": cfg.get("acts", []),
                 "format_default": cfg.get("format_default", "raw"),
                 "available": cfg.get("model") is not None,
                 "train_hint": cfg.get("train_hint", ""),
                 "K": cfg["model"][3] if cfg.get("model") else None,
                 "params": cfg.get("params")}
                for mid, cfg in modes.items()
            ],
        }

    class Handler(http.server.BaseHTTPRequestHandler):
        def _send(self, status, content_type, body: bytes):
            self.send_response(status)
            self.send_header("Content-Type", content_type)
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

        def _send_json(self, obj, status=200):
            self._send(status, "application/json; charset=utf-8",
                       json.dumps(obj).encode("utf-8"))

        def _send_html_error(self, status, msg):
            self._send(status, "text/html; charset=utf-8",
                       marginalia.html_error_page(status, msg))

        def _mode_cfg(self, mode, html_errors=False):
            """Resolve a mode id to a usable config, or send the right error
            (400 unknown / 503 absent) and return None. JSON errors for the
            /api/ routes; HTML for the browser-facing /corpus and /source."""
            if mode not in modes:
                msg = f"unknown mode: {mode!r}"
                if html_errors:
                    self._send_html_error(400, msg)
                else:
                    self._send_json({"error": msg}, status=400)
                return None
            cfg = modes[mode]
            if cfg.get("model") is None:
                hint = cfg.get("train_hint", "")
                msg = f"no trained model for '{mode}' -- run `{hint}` first"
                if html_errors:
                    self._send_html_error(503, msg)
                else:
                    self._send_json({"error": msg}, status=503)
                return None
            return cfg

        def _read_json_body(self):
            try:
                length = int(self.headers.get("Content-Length") or 0)
            except ValueError:
                length = 0
            if length <= 0 or length > 1_000_000:
                self._send_json({"error": "missing or oversized request body"},
                                status=400)
                return None
            try:
                return json.loads(self.rfile.read(length).decode("utf-8"))
            except (UnicodeDecodeError, json.JSONDecodeError):
                self._send_json({"error": "body must be valid JSON"},
                                status=400)
                return None

        def do_POST(self):
            parsed = urllib.parse.urlparse(self.path)
            if parsed.path == "/api/turn":
                body = self._read_json_body()
                if body is None:
                    return
                if not isinstance(body, dict):
                    self._send_json({"error": "body must be a JSON object"},
                                    status=400)
                    return
                cfg = self._mode_cfg(body.get("mode", default_mode))
                if cfg is None:
                    return
                req, err = parse_turn_request(body)
                if err:
                    self._send_json({"error": err[1]}, status=err[0])
                    return
                try:
                    result = run_turn(cfg["model"], req["tape"],
                                      req["sampling"],
                                      files=cfg.get("files", ()))
                except ValueError as e:   # defensive: e.g. every id banned
                    self._send_json({"error": str(e)}, status=400)
                    return
                except Exception as e:
                    self._send_json({"error": f"generation failed: {e}"},
                                    status=500)
                    return
                result["format"] = req["format"]
                self._send_json(result)
            elif parsed.path == "/api/saliency":
                body = self._read_json_body()
                if body is None:
                    return
                if not isinstance(body, dict):
                    self._send_json({"error": "body must be a JSON object"},
                                    status=400)
                    return
                cfg = self._mode_cfg(body.get("mode", default_mode))
                if cfg is None:
                    return
                text, pos = body.get("text"), body.get("pos")
                if not isinstance(text, str) or not isinstance(pos, int) \
                        or isinstance(pos, bool):
                    self._send_json({"error": "need string text and integer "
                                              "pos"}, status=400)
                    return
                if len(text) > MAX_TAPE_CHARS + MAX_CONTINUATION:
                    self._send_json({"error": "text too long"}, status=413)
                    return
                p, stoi, itos, K = cfg["model"]
                try:
                    # n_continuation=0: the client sends the FULL generated
                    # text (tape + continuation), so nothing is re-sampled --
                    # saliency describes exactly the response on screen.
                    result = colophon.context_saliency(p, stoi, itos, K,
                                                       text, pos,
                                                       n_continuation=0)
                except IndexError as e:
                    self._send_json({"error": str(e)}, status=400)
                    return
                except Exception as e:
                    self._send_json({"error": f"analysis failed: {e}"},
                                    status=500)
                    return
                self._send_json(result)
            else:
                self.send_error(404)

        def do_GET(self):
            parsed = urllib.parse.urlparse(self.path)
            if parsed.path == "/api/modes":
                self._send_json(_modes_payload())
            elif parsed.path == "/api/scorecard":
                self._send_json(colophon.scorecard_section())
            elif parsed.path == "/source":
                qs = urllib.parse.parse_qs(parsed.query)
                mode = qs.get("mode", [default_mode])[0]
                cfg = self._mode_cfg(mode, html_errors=True)
                if cfg is None:
                    return
                line_raw = qs.get("line", [None])[0]
                line = None
                if line_raw is not None:
                    try:
                        line = int(line_raw)
                    except ValueError:
                        self._send_html_error(400, "line must be an integer")
                        return
                filename = qs.get("file", [""])[0]
                files = cfg.get("files", ())
                text = next((t for name, t in files if name == filename), None)
                if text is None:
                    self._send_html_error(
                        404, f"no file named {filename!r} in this mode's corpus")
                    return
                body = marginalia.source_page(
                    cfg.get("label", ""), filename, text, line=line,
                    note=cfg.get("source_note", ""),
                    url=cfg.get("source_url", ""),
                    sha=marginalia.corpus_sha256(files) if files else "")
                self._send(200, "text/html; charset=utf-8", body.encode("utf-8"))
            elif parsed.path.startswith("/api/"):
                self.send_error(404)
            else:
                self._serve_static(parsed.path)

        def _serve_static(self, path):
            """Serve the built front-end from dist_dir. realpath containment
            blocks traversal; a missing bundle yields a build-help page
            instead of a mystery 404."""
            rel = path.lstrip("/") or "index.html"
            root = os.path.realpath(dist_dir)
            full = os.path.realpath(os.path.join(root, rel))
            if full != root and not full.startswith(root + os.sep):
                self.send_error(404)
                return
            if os.path.isdir(full):
                full = os.path.join(full, "index.html")
            if not os.path.exists(full):
                if not os.path.exists(os.path.join(root, "index.html")):
                    self._send(200, "text/html; charset=utf-8",
                               MISSING_DIST_HTML.encode("utf-8"))
                    return
                self.send_error(404)
                return
            ctype = mimetypes.guess_type(full)[0] or "application/octet-stream"
            with open(full, "rb") as f:
                self._send(200, ctype, f.read())

    return Handler


def main():
    ap = argparse.ArgumentParser(
        description="Incipit -- multiturn glass-box chat for Colophon.")
    ap.add_argument("--osai-npz",
                    default=os.path.join(colophon.HERE, colophon.WEIGHTS_FILE))
    ap.add_argument("--osai-src", default=colophon.DEFAULT_SRC)
    ap.add_argument("--elements64-npz",
                    default=os.path.join(colophon.HERE, "elements_k64.npz"))
    ap.add_argument("--elements-src",
                    default=os.path.join(colophon.HERE, "teaching_data",
                                         "elements"))
    ap.add_argument("--dialogue-npz",
                    default=os.path.join(colophon.HERE, "dialogue_k64.npz"))
    ap.add_argument("--dialogue-src",
                    default=os.path.join(colophon.HERE, "teaching_data",
                                         "dialogue"))
    ap.add_argument("--host", default="127.0.0.1", help="local-only by default")
    ap.add_argument("--port", type=int, default=8790)
    args = ap.parse_args()

    sources = {"elements64": (args.elements64_npz, args.elements_src),
               "dialogue": (args.dialogue_npz, args.dialogue_src),
               "osai": (args.osai_npz, args.osai_src)}
    modes = {}
    for mode_id, meta in MODE_META.items():
        npz_path, src_dir = sources[mode_id]
        model, files = marginalia._load_mode(mode_id, npz_path, src_dir)
        modes[mode_id] = {"model": model, "files": files,
                          "params": colophon.n_params(model[0]) if model
                                    else None,
                          **meta}

    default_mode = DEFAULT_MODE
    if modes[default_mode]["model"] is None:
        available = [m for m, c in modes.items() if c["model"] is not None]
        default_mode = available[0] if available else DEFAULT_MODE

    httpd = http.server.HTTPServer((args.host, args.port),
                                   make_handler(modes,
                                                default_mode=default_mode))
    print(f"Incipit serving at http://{args.host}:{args.port}  "
          f"(Ctrl+C to stop)")
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    main()
